FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg
RUN npm install -g nodemon

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["nodemon", "--legacy-watch", "--watch", ".", "--ext", "js,mjs,cjs,json", "server.js"]
